# Generated by Django 4.1.6 on 2023-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.IntegerField(null=True),
        ),
    ]
